### ISSUE TITLE
about setting up

### ISSUE THREAD

**Issue by t-cool** [defaultxr/cl-collider-tutorial#1]
Thank you for writing a tutorial!
When setting up cl-collider, I think it's better to in-package :sc-user, and evaluate :in-readtable function.

(in-package :sc-user)
(named-readtables:in-readtable :sc)

What do you think?

**Comment by defaultxr** [comment]
Good call, I totally forgot about that. I have my own functions to automatically start up the server for me, so I totally forgot about the :sc-user package. I'll fix that now.

**Comment by defaultxr** [comment]
As for named-readtables, just being in the SC-USER package should allow the syntax sugar to work with no extra configuration.

**Comment by t-cool** [comment]
Thank you for taking your time.
I tried on Emacs, as you said, we don't have to evaluate (named-readtables:in-readtable :sc).
